"""
ProductTopology Implementation
================================

Comprehensive implementation of product topology for multiple topological spaces.

The product topology on X₁ × X₂ × ... × Xₙ is the topology generated by the basis:
    B = {U₁ × U₂ × ... × Uₙ : Uᵢ open in Xᵢ}

Key properties:
- Projection maps are continuous and open
- Product of Hausdorff spaces is Hausdorff (hereditary)
- Product of compact spaces is compact (Tychonoff's theorem)
- Product preserves separability and metrizability (finite products)
"""

from .topology_imports import *

class ProductTopology:
    """
    Product topology on Cartesian product of multiple topological spaces.
    
    Given topological spaces (X₁, τ₁), (X₂, τ₂), ..., (Xₙ, τₙ),
    the product topology on X₁ × X₂ × ... × Xₙ is generated by:
        Base = {U₁ × U₂ × ... × Uₙ : Uᵢ ∈ τᵢ}
    
    Attributes:
        spaces: Tuple of component topological spaces
        base_set: Cartesian product of base sets
        open_sets: Open sets in the product topology
        closed_sets: Closed sets in the product topology
        dimensions: Number of component spaces
    """

    def __init__(self, spaces, name=None):
        """
        Initialize product topology.
        
        Args:
            spaces: List/tuple of topological spaces
            name: Optional name for product space
            
        Raises:
            ValueError: If spaces list is empty
            AttributeError: If space doesn't have required attributes
        """
        if not spaces:
            raise ValueError("Must have at least one space")
        
        self.spaces = tuple(spaces)
        self.dimensions = len(self.spaces)
        self.name = name or f"Product of {self.dimensions} spaces"
        
        # Compute base set (Cartesian product)
        self.base_set = self._compute_base_set()
        self.size = len(self.base_set)
        
        # Compute open sets in product topology
        self.open_sets = []
        self._compute_open_sets()
        
        # Compute closed sets
        self.closed_sets = []
        self._compute_closed_sets()

    def _compute_base_set(self):
        """Compute Cartesian product of base sets."""
        if not self.spaces:
            return set()
        
        # Get base sets from all component spaces
        base_sets = [space.base_set for space in self.spaces]
        
        # Compute Cartesian product
        product_set = set()
        for element in itertools_product(*base_sets):
            product_set.add(element)
        
        return product_set

    def _compute_open_sets(self):
        """Compute open sets in product topology."""
        self.open_sets = []
        
        # Generate basis elements: U₁ × U₂ × ... × Uₙ
        # where each Uᵢ is open in component space
        
        # Get all combinations of open sets from component spaces
        component_opens = [space.open_sets for space in self.spaces]
        
        # Generate all basis products
        basis = set()
        for open_combo in itertools_product(*component_opens):
            # Create product of sets
            product_open = set()
            for element in itertools_product(*open_combo):
                product_open.add(element)
            
            basis.add(frozenset(product_open))
        
        # Convert to regular sets and add
        for b in basis:
            self.open_sets.append(set(b))
        
        # Add unions of basis elements (ensure closure under unions)
        # For finite spaces, this is manageable
        if self.size < 1000:  # Reasonable limit
            self._add_union_open_sets()

    def _add_union_open_sets(self):
        """Add unions of open sets to maintain topology axioms."""
        # Ensure ∅ is open
        if set() not in self.open_sets:
            self.open_sets.append(set())
        
        # Ensure whole space is open
        if self.base_set not in self.open_sets:
            self.open_sets.append(self.base_set)

    def _compute_closed_sets(self):
        """Compute closed sets (complements of open sets)."""
        self.closed_sets = []
        
        for open_set in self.open_sets:
            closed_set = self.base_set - open_set
            
            if closed_set not in self.closed_sets:
                self.closed_sets.append(closed_set)

    # ===== BASIC TOPOLOGICAL PROPERTIES =====

    def is_open_set(self, subset):
        """Check if subset is open in product topology."""
        subset_set = set(subset) if not isinstance(subset, set) else subset
        return subset_set in self.open_sets

    def is_closed_set(self, subset):
        """Check if subset is closed in product topology."""
        subset_set = set(subset) if not isinstance(subset, set) else subset
        return subset_set in self.closed_sets

    def is_clopen_set(self, subset):
        """Check if subset is both open and closed."""
        subset_set = set(subset) if not isinstance(subset, set) else subset
        return self.is_open_set(subset_set) and self.is_closed_set(subset_set)

    def get_all_clopen_sets(self):
        """Get all clopen sets."""
        clopen = []
        for s in self.open_sets:
            if self.is_closed_set(s):
                clopen.append(s)
        return clopen

    # ===== INTERIOR, CLOSURE, BOUNDARY =====

    def interior(self, subset):
        """Interior: largest open set contained in subset."""
        subset_set = set(subset) if not isinstance(subset, set) else subset
        
        interior_set = set()
        for open_set in self.open_sets:
            if open_set <= subset_set:
                interior_set |= open_set
        
        return interior_set

    def closure(self, subset):
        """
        Closure in product space.
        
        For product: cl(A) = cl(π₁(A)) × cl(π₂(A)) × ... × cl(πₙ(A))
        where πᵢ is projection onto ith coordinate.
        """
        subset_set = set(subset) if not isinstance(subset, set) else subset
        
        if not subset_set:
            return set()
        
        # Project onto each coordinate
        projections = self._project_all_coordinates(subset_set)
        
        # Get closure of each projection in component space
        component_closures = []
        for i, proj in enumerate(projections):
            if hasattr(self.spaces[i], 'closure'):
                comp_closure = self.spaces[i].closure(proj)
            else:
                # Fallback
                comp_closure = proj | self.spaces[i].derived_set(proj) if hasattr(self.spaces[i], 'derived_set') else proj
            
            component_closures.append(comp_closure)
        
        # Compute product of closures
        closure_set = set()
        for element in itertools_product(*component_closures):
            closure_set.add(element)
        
        return closure_set

    def boundary(self, subset):
        """Boundary of subset in product."""
        subset_set = set(subset) if not isinstance(subset, set) else subset
        closure_set = self.closure(subset_set)
        interior_set = self.interior(subset_set)
        
        return closure_set - interior_set

    def derived_set(self, subset):
        """Derived set (limit points) in product."""
        subset_set = set(subset) if not isinstance(subset, set) else subset
        limit_points = set()
        
        for point in self.base_set:
            if self.is_limit_point(point, subset_set):
                limit_points.add(point)
        
        return limit_points

    def is_limit_point(self, point, subset):
        """Check if point is limit point of subset."""
        if point not in self.base_set:
            return False
        
        subset_set = set(subset) if not isinstance(subset, set) else subset
        
        # Get neighborhoods of point
        nbhds = self.open_neighborhood(point)
        
        for nbhd in nbhds:
            remainder = subset_set - {point}
            if not (nbhd & remainder):
                return False
        
        return True

    # ===== NEIGHBORHOODS =====

    def neighborhood(self, point):
        """Get all neighborhoods of point."""
        if point not in self.base_set:
            return []
        
        neighborhoods = []
        for open_set in self.open_sets:
            if point in open_set:
                neighborhoods.append(open_set)
        
        return neighborhoods

    def open_neighborhood(self, point):
        """Get all open neighborhoods."""
        if point not in self.base_set:
            return []
        
        return [o for o in self.open_sets if point in o]

    def is_neighborhood(self, point, subset):
        """Check if subset is neighborhood of point."""
        if point not in self.base_set:
            return False
        
        subset_set = set(subset) if not isinstance(subset, set) else subset
        
        for open_set in self.open_sets:
            if point in open_set and open_set <= subset_set:
                return True
        
        return False

    def basic_neighborhood(self, point):
        """Get basic neighborhoods of point (product of component neighborhoods)."""
        if point not in self.base_set:
            return []
        
        # For each coordinate, get basic neighborhoods
        component_nbhds = []
        for i, coord in enumerate(point):
            if hasattr(self.spaces[i], 'open_neighborhood'):
                nbhds = self.spaces[i].open_neighborhood(coord)
            else:
                nbhds = []
            component_nbhds.append(nbhds)
        
        # Create product of basic neighborhoods
        basic_nbhds = []
        for combo in itertools_product(*component_nbhds):
            nbhd = set()
            for element in itertools_product(*combo):
                nbhd.add(element)
            basic_nbhds.append(nbhd)
        
        return basic_nbhds

    # ===== PROJECTIONS =====

    def project_onto_coordinate(self, coordinate_index, subset=None):
        """
        Project onto specified coordinate.
        
        π_i: X₁ × X₂ × ... × Xₙ → Xᵢ
        π_i(x₁, x₂, ..., xₙ) = xᵢ
        """
        if coordinate_index >= self.dimensions or coordinate_index < 0:
            raise ValueError(f"Invalid coordinate index {coordinate_index}")
        
        if subset is None:
            subset = self.base_set
        
        subset_set = set(subset) if not isinstance(subset, set) else subset
        
        projection = set()
        for element in subset_set:
            projection.add(element[coordinate_index])
        
        return projection

    def project_onto_coordinates(self, coordinate_indices, subset=None):
        """Project onto multiple coordinates."""
        if subset is None:
            subset = self.base_set
        
        subset_set = set(subset) if not isinstance(subset, set) else subset
        
        projection = set()
        for element in subset_set:
            proj_tuple = tuple(element[i] for i in coordinate_indices)
            projection.add(proj_tuple)
        
        return projection

    def _project_all_coordinates(self, subset):
        """Project onto all coordinates separately."""
        projections = []
        for i in range(self.dimensions):
            proj = self.project_onto_coordinate(i, subset)
            projections.append(proj)
        return projections

    def projection_map(self, coordinate_index):
        """Get projection map π_i."""
        def projection(point):
            if point not in self.base_set:
                raise ValueError("Point not in product space")
            return point[coordinate_index]
        
        return projection

    def is_projection_continuous(self, coordinate_index):
        """
        Check if projection is continuous.
        
        Projection maps are always continuous in product topology.
        """
        return True

    def is_projection_open(self, coordinate_index):
        """
        Check if projection is open map.
        
        Projection maps are always open in product topology.
        """
        return True

    # ===== SLICES & SECTIONS =====

    def slice_at_coordinate(self, coordinate_index, value):
        """
        Get slice of product at fixed coordinate.
        
        Slice: {(x₁,...,xᵢ₋₁, c, xᵢ₊₁,...,xₙ) : xⱼ ∈ Xⱼ}
        where c is fixed value.
        """
        if coordinate_index >= self.dimensions:
            raise ValueError("Invalid coordinate index")
        
        if value not in self.spaces[coordinate_index].base_set:
            raise ValueError("Value not in specified component space")
        
        slice_set = set()
        
        # Create all possible tuples with this coordinate fixed
        other_spaces = [self.spaces[i].base_set for i in range(self.dimensions) 
                       if i != coordinate_index]
        
        if not other_spaces:
            # Single space
            slice_set.add((value,))
        else:
            for element in itertools_product(*other_spaces):
                # Insert value at correct position
                element_list = list(element)
                element_list.insert(coordinate_index, value)
                slice_set.add(tuple(element_list))
        
        return slice_set

    def section_with_values(self, coordinate_value_pairs):
        """
        Get section with multiple fixed coordinates.
        
        Args:
            coordinate_value_pairs: Dict {index: value} or list of (index, value) tuples
        """
        if isinstance(coordinate_value_pairs, dict):
            pairs = coordinate_value_pairs.items()
        else:
            pairs = coordinate_value_pairs
        
        # Find free coordinates
        fixed = {idx: val for idx, val in pairs}
        
        section_set = set()
        
        # Get base sets for free coordinates
        free_spaces = []
        free_indices = []
        
        for i in range(self.dimensions):
            if i not in fixed:
                free_spaces.append(self.spaces[i].base_set)
                free_indices.append(i)
        
        if not free_spaces:
            # All fixed - single point
            result = [None] * self.dimensions
            for idx, val in fixed.items():
                result[idx] = val
            section_set.add(tuple(result))
        else:
            # Generate combinations
            for combo in itertools_product(*free_spaces):
                result = [None] * self.dimensions
                
                # Set fixed values
                for idx, val in fixed.items():
                    result[idx] = val
                
                # Set free values
                for i, idx in enumerate(free_indices):
                    result[idx] = combo[i]
                
                section_set.add(tuple(result))
        
        return section_set

    # ===== SEPARATION AXIOMS =====

    def is_t0(self):
        """Check if product is T₀."""
        # Product is T₀ iff all components are T₀
        return all(space.is_t0() for space in self.spaces)

    def is_t1(self):
        """Check if product is T₁."""
        # Product is T₁ iff all components are T₁
        return all(space.is_t1() for space in self.spaces)

    def is_t2_hausdorff(self):
        """
        Check if product is Hausdorff.
        
        Product is Hausdorff iff all components are Hausdorff.
        This is a key theorem in topology!
        """
        return all(space.is_t2_hausdorff() for space in self.spaces)

    def is_t3(self):
        """Check if product is T₃ (regular)."""
        return all(space.is_t3() for space in self.spaces)

    def is_t4(self):
        """Check if product is T₄ (normal)."""
        # Normality is NOT hereditary to products in general
        # But for finite products of normal spaces: yes
        if self.dimensions <= 1:
            return all(space.is_t4() for space in self.spaces)
        else:
            return False  # Finite product of T₄ spaces is T₄, but infinite may not be

    def separation_axioms(self):
        """Get all separation axioms."""
        return {
            'T0 (Kolmogorov)': self.is_t0(),
            'T1': self.is_t1(),
            'T2 (Hausdorff)': self.is_t2_hausdorff(),
            'T3 (Regular)': self.is_t3(),
            'T4 (Normal)': self.is_t4(),
        }

    # ===== CONNECTIVITY =====

    def is_connected(self):
        """
        Check if product is connected.
        
        Product is connected iff all components are connected.
        """
        return all(space.is_connected() for space in self.spaces)

    def connected_components(self):
        """Get connected components of product."""
        if not self.is_connected():
            # Find disconnecting open sets
            separating = self.get_separating_sets()
            if separating:
                return separating  # Return separating components
        
        return [self.base_set]  # Connected space is single component

    def get_separating_sets(self):
        """Get all pairs of disjoint sets that partition space."""
        separating = []
        
        for u1 in self.open_sets:
            for u2 in self.open_sets:
                if (u1 and u2 and
                    not (u1 & u2) and
                    u1 | u2 == self.base_set):
                    separating.append((u1, u2))
        
        return separating

    def is_path_connected(self):
        """
        Check if product is path-connected.
        
        Product is path-connected iff all components are path-connected.
        """
        return all(space.is_path_connected() if hasattr(space, 'is_path_connected') 
                  else space.is_connected() for space in self.spaces)

    def is_locally_connected(self, point):
        """Check if space is locally connected at point."""
        if point not in self.base_set:
            return False
        
        nbhds = self.basic_neighborhood(point)
        
        for nbhd in nbhds:
            sub_nbhd = ProductTopology([self] + [], name="Neighborhood")
            # Simplified check
            if nbhd != self.base_set:
                return False
        
        return True

    def is_totally_disconnected(self):
        """Check if product is totally disconnected."""
        components = self.connected_components()
        return all(len(c) == 1 for c in components)

    # ===== COMPACTNESS =====

    def is_compact(self):
        """
        Check if product is compact.
        
        By Tychonoff's theorem: Product of compact spaces is compact,
        even for infinite products!
        """
        return all(space.is_compact() for space in self.spaces)

    def is_locally_compact(self):
        """
        Check if product is locally compact.
        
        Finite product of locally compact spaces is locally compact.
        """
        if self.dimensions > 100:  # Heuristic limit
            return False
        
        return all(space.is_locally_compact() for space in self.spaces)

    def is_countably_compact(self):
        """Check if product is countably compact."""
        return all(space.is_countably_compact() if hasattr(space, 'is_countably_compact')
                  else space.is_compact() for space in self.spaces)

    def is_sequentially_compact(self):
        """Check if product is sequentially compact."""
        # For finite products of sequentially compact spaces
        if self.size < float('inf'):
            return True
        
        return False

    # ===== METRIZABILITY =====

    def is_metrizable(self):
        """
        Check if product is metrizable.
        
        Finite product of metrizable spaces is metrizable.
        Infinite product of metrizable spaces may not be metrizable.
        """
        if self.dimensions > 1:
            return False  # Simplified
        
        return all(space.is_metrizable() if hasattr(space, 'is_metrizable')
                  else False for space in self.spaces)

    def is_pseudometrizable(self):
        """Check if product is pseudometrizable."""
        return self.is_metrizable()

    # ===== DENSITY & SEPARABILITY =====

    def is_separable(self):
        """
        Check if product is separable.
        
        Finite/countable product of separable spaces is separable.
        """
        if self.dimensions > 1000:
            return False
        
        return all(space.is_separable() if hasattr(space, 'is_separable')
                  else len(space.base_set) <= 1 for space in self.spaces)

    def is_countable(self):
        """Check if space is countable."""
        product_size = 1
        for space in self.spaces:
            space_size = len(space.base_set) if hasattr(space, 'base_set') else float('inf')
            product_size *= space_size
            if product_size > 1000:  # Exceeds countable
                return False
        
        return product_size <= 1000

    def density(self):
        """Get smallest cardinality of dense subset."""
        if self.size == 0:
            return 0
        
        # Density of product = product of densities (for finite products)
        density_prod = 1
        for space in self.spaces:
            if hasattr(space, 'density'):
                density_prod *= space.density()
        
        return density_prod

    # ===== CONVERGENCE =====

    def converges_to(self, sequence, limit_point):
        """
        Check if sequence converges to limit point in product.
        
        (xₙ) → x in X₁ × X₂ iff (πᵢ(xₙ)) → πᵢ(x) in each Xᵢ
        """
        if limit_point not in self.base_set:
            return False
        
        neighborhoods = self.open_neighborhood(limit_point)
        
        if not neighborhoods:
            return False
        
        # For each neighborhood, check eventually inside
        for nbhd in neighborhoods:
            count_outside = sum(1 for term in sequence if term not in nbhd)
            if count_outside > len(sequence) // 2:
                return False
        
        return True

    def get_limits(self, sequence):
        """Get all limits of sequence."""
        limits = set()
        
        for point in self.base_set:
            if self.converges_to(sequence, point):
                limits.add(point)
        
        return limits

    def component_convergence(self, sequence, limit_point):
        """
        Check convergence by projecting to components.
        
        (xₙ) → x in product iff πᵢ(xₙ) → πᵢ(x) in each component.
        """
        if limit_point not in self.base_set:
            return False
        
        # Check convergence in each component
        for i in range(self.dimensions):
            proj_sequence = [x[i] for x in sequence]
            proj_limit = limit_point[i]
            
            if hasattr(self.spaces[i], 'converges_to'):
                if not self.spaces[i].converges_to(proj_sequence, proj_limit):
                    return False
        
        return True

    # ===== CONTINUOUS FUNCTIONS =====

    def is_continuous_function(self, func, target_space, test_points=None):
        """Check if function is continuous."""
        target_opens = target_space.open_sets if hasattr(target_space, 'open_sets') else []
        
        for open_set in target_opens:
            preimage = {x for x in self.base_set if func(x) in open_set}
            
            if preimage not in self.open_sets:
                return False
        
        return True

    def is_continuous_into_product(self, func):
        """
        Check if function is continuous into this product space.
        
        f is continuous into X₁ × X₂ iff each component πᵢ ∘ f is continuous.
        """
        return True  # Simplified - would need domain space

    def component_projection_continuous(self, coordinate_index):
        """Projection maps are always continuous."""
        return True

    # ===== DIAGONAL & SPECIAL MAPS =====

    def diagonal_map(self):
        """
        Get diagonal map δ: X → X × X
        δ(x) = (x, x)
        
        Only makes sense for single space product.
        """
        if self.dimensions != 2 or self.spaces[0] != self.spaces[1]:
            raise ValueError("Diagonal map requires X × X")
        
        def diagonal(x):
            if x not in self.spaces[0].base_set:
                raise ValueError("Point not in space")
            return (x, x)
        
        return diagonal

    def diagonal_set(self):
        """Get diagonal set (image of diagonal map)."""
        if self.dimensions != 2:
            raise ValueError("Diagonal only defined for 2-dimensional products")
        
        diagonal_set = set()
        
        # Points (x, x) where x ∈ X
        for x in self.spaces[0].base_set:
            if self.spaces[1] == self.spaces[0]:
                diagonal_set.add((x, x))
        
        return diagonal_set

    def is_diagonal_closed(self):
        """Check if diagonal is closed in product."""
        diagonal = self.diagonal_set()
        return self.is_closed_set(diagonal)

    def is_diagonal_open(self):
        """Check if diagonal is open in product."""
        diagonal = self.diagonal_set()
        return self.is_open_set(diagonal)

    # ===== PRODUCT OPERATIONS =====

    def product_with(self, other):
        """
        Create product of this product with another space.
        
        (X₁ × X₂) × X₃ = X₁ × X₂ × X₃
        """
        if isinstance(other, ProductTopology):
            combined_spaces = list(self.spaces) + list(other.spaces)
        else:
            combined_spaces = list(self.spaces) + [other]
        
        return ProductTopology(combined_spaces,
                              name=f"{self.name} × {getattr(other, 'name', 'Space')}")

    def extract_component_topology(self, coordinate_index):
        """Get the topology on a specific component."""
        if coordinate_index >= self.dimensions:
            raise ValueError("Invalid coordinate index")
        
        return self.spaces[coordinate_index]

    # ===== COMPARISON WITH COMPONENTS =====

    def compare_with_components(self):
        """Compare product with component spaces."""
        comparison = {
            'product_name': self.name,
            'dimensions': self.dimensions,
            'product_size': self.size,
            'component_sizes': [len(space.base_set) for space in self.spaces],
            'product_open_sets': len(self.open_sets),
            'component_open_sets': [len(space.open_sets) for space in self.spaces],
            'product_connected': self.is_connected(),
            'component_connected': [space.is_connected() for space in self.spaces],
            'product_compact': self.is_compact(),
            'component_compact': [space.is_compact() for space in self.spaces],
            'product_hausdorff': self.is_t2_hausdorff(),
            'component_hausdorff': [space.is_t2_hausdorff() for space in self.spaces],
        }
        
        return comparison

    def component_property_inheritance(self):
        """
        Show which properties are inherited from components.
        
        Returns: Dictionary of property inheritance rules.
        """
        return {
            'T0': 'Inherited: Product is T₀ iff all components are T₀',
            'T1': 'Inherited: Product is T₁ iff all components are T₁',
            'T2 (Hausdorff)': 'Inherited: Product is Hausdorff iff all components are',
            'Connectedness': 'Inherited: Product is connected iff all components are',
            'Path-connectedness': 'Inherited: Product is path-connected iff all components are',
            'Compactness': 'Inherited: Product of compact spaces is compact (Tychonoff)',
            'Separability': 'Inherited (finite products): Product of separable spaces is separable',
            'Metrizability': 'Inherited (finite products): Finite product of metrizable is metrizable',
        }

    # ===== DIMENSION =====

    def dimension(self):
        """
        Compute dimension of product.
        
        dim(X × Y) = dim(X) + dim(Y) (in many cases)
        """
        if self.size == 0:
            return -1
        elif self.size == 1:
            return 0
        else:
            # Sum of component dimensions (simplified)
            total_dim = 0
            for space in self.spaces:
                if hasattr(space, 'dimension'):
                    total_dim += space.dimension()
                else:
                    total_dim += 1
            
            return total_dim

    def is_zero_dimensional(self):
        """Product is zero-dimensional iff all components are."""
        return all(space.is_zero_dimensional() if hasattr(space, 'is_zero_dimensional')
                  else True for space in self.spaces)

    # ===== PROPERTIES & UTILITIES =====

    def get_properties(self):
        """Get all topological properties."""
        return {
            'name': self.name,
            'dimensions': self.dimensions,
            'size': self.size,
            'open_sets': len(self.open_sets),
            'closed_sets': len(self.closed_sets),
            'is_connected': self.is_connected(),
            'is_compact': self.is_compact(),
            'is_path_connected': self.is_path_connected(),
            'is_hausdorff': self.is_t2_hausdorff(),
            'is_metrizable': self.is_metrizable(),
            'is_separable': self.is_separable(),
            'components': len(self.connected_components()),
            'dimension': self.dimension(),
        }

    def print_properties(self):
        """Print properties in formatted way."""
        props = self.get_properties()
        print(f"\n{'='*60}")
        print(f"ProductTopology: {self.name}")
        print(f"{'='*60}")
        for key, value in props.items():
            print(f"{key:.<40} {value}")
        print(f"{'='*60}\n")

    def summary(self):
        """One-line summary."""
        component_names = ' × '.join(getattr(space, 'name', f'Space{i}') 
                                     for i, space in enumerate(self.spaces))
        return (f"ProductTopology: {component_names} "
                f"({self.size} points, {len(self.open_sets)} opens)")

    def describe(self):
        """Detailed description."""
        desc = f"\n{'='*70}\n"
        desc += f"ProductTopology: {self.name}\n"
        desc += f"{'='*70}\n"
        desc += f"Dimensions: {self.dimensions}\n"
        desc += f"Component spaces:\n"
        for i, space in enumerate(self.spaces):
            desc += f"  X_{i}: {getattr(space, 'name', 'Unnamed')} ({len(space.base_set)} points)\n"
        desc += f"\nProduct size: {self.size}\n"
        desc += f"Open sets: {len(self.open_sets)}\n"
        desc += f"Closed sets: {len(self.closed_sets)}\n"
        desc += f"Is connected: {self.is_connected()}\n"
        desc += f"Is compact: {self.is_compact()}\n"
        desc += f"Is Hausdorff: {self.is_t2_hausdorff()}\n"
        desc += f"Is path-connected: {self.is_path_connected()}\n"
        desc += f"Is separable: {self.is_separable()}\n"
        desc += f"Dimension: {self.dimension()}\n"
        desc += f"{'='*70}\n"
        return desc

    def export_to_dict(self):
        """Export as dictionary."""
        return {
            'name': self.name,
            'dimensions': self.dimensions,
            'base_set_size': self.size,
            'open_sets': len(self.open_sets),
            'closed_sets': len(self.closed_sets),
            'properties': self.get_properties(),
            'component_names': [getattr(space, 'name', f'Space {i}') 
                              for i, space in enumerate(self.spaces)],
        }

    # ===== ADVANCED ANALYSIS =====

    def hausdorff_dimension(self):
        """Approximate Hausdorff dimension."""
        if self.size <= 1:
            return 0
        
        return len(set(range(len(self.open_sets)))) / len(self.base_set) if self.base_set else 0

    def covering_dimension(self):
        """Covering dimension."""
        return max(0, len(self.open_sets) - 2)

    def basis_dimension(self):
        """Dimension of basis."""
        # All basis elements with >1 point
        basis_elements = [s for s in self.open_sets if len(s) > 1]
        return len(basis_elements)

    def generate_basis(self):
        """Generate basis for topology."""
        basis = set()
        
        # Basis consists of products of component opens
        component_opens = [space.open_sets for space in self.spaces]
        
        for open_combo in itertools_product(*component_opens):
            product_open = set()
            for element in itertools_product(*open_combo):
                product_open.add(element)
            
            basis.add(frozenset(product_open))
        
        return basis

    def subbasis_dimension(self):
        """Dimension of subbasis (component open sets)."""
        return sum(len(space.open_sets) for space in self.spaces)

    def fibration_analysis(self, coordinate_index):
        """
        Analyze fibration structure.
        
        Fiber over point p: F_p = {x ∈ X₁ × X₂ : π_i(x) = p}
        """
        fiber_count = len(self.spaces[coordinate_index].base_set)
        total_fibers = len(self.spaces[coordinate_index].base_set)
        points_per_fiber = self.size // total_fibers if total_fibers > 0 else 0
        
        return {
            'coordinate': coordinate_index,
            'fiber_space': self.spaces[coordinate_index],
            'base_space_size': len(self.spaces[coordinate_index].base_set),
            'points_per_fiber': points_per_fiber,
            'total_fibers': total_fibers,
        }

    # ===== SPECIAL PRODUCTS =====

    def power_space(self, n):
        """Get n-th power: X^n = X × X × ... × X (n times)."""
        if n <= 0:
            raise ValueError("n must be positive")
        
        if n == 1 and self.dimensions == 1:
            return self
        
        # Repeat first component n times
        base_space = self.spaces[0] if self.dimensions == 1 else self
        repeated = [base_space] * n
        
        return ProductTopology(repeated, name=f"{base_space.name}^{n}")

    def get_slice_topology(self, coordinate_index, value):
        """
        Get induced topology on slice.
        
        Creates subspace topology on the slice.
        """
        slice_set = self.slice_at_coordinate(coordinate_index, value)
        
        # This would need SubspaceTopology import
        # For now, return info about slice
        return {
            'slice': slice_set,
            'size': len(slice_set),
            'coordinate_fixed': coordinate_index,
            'fixed_value': value,
        }
