from .convertors import *

__init__ = {
    "UnitConvertor": UnitConvertor,
    "TemperatureConvertor": TemperatureConvertor,
    "TimeConvertor": TimeConvertor,
    "DataStorageConvertor": DataStorageConvertor,
    "SpeedConvertor": SpeedConvertor,
    "PressureConvertor": PressureConvertor,
    "EnergyConvertor": EnergyConvertor,
    "VolumeConvertor": VolumeConvertor,
    "AngleConvertor": AngleConvertor,
    "FrequencyConvertor": FrequencyConvertor,
    "CubicConvertor": CubicConvertor,
    "LightConvertor": LightConvertor,
    "SoundConvertor": SoundConvertor,
    "DataRateConvertor": DataRateConvertor,
    "ForceConvertor": ForceConvertor,
    "MagneticFieldConvertor": MagneticFieldConvertor,
    "RadiationConvertor": RadiationConvertor,
    "DataDensityConvertor": DataDensityConvertor,
    "AreaConvertor": AreaConvertor,
    "LengthConvertor": LengthConvertor,
    "WeightConvertor": WeightConvertor,
    "WorkConvertor": WorkConvertor,
    "PowerConvertor": PowerConvertor,
    "MiscConvert": MiscConvert,
    "GeometryConvert": GeometryConvert,
    "ResolutionConvert": ResolutionConvert,
    "HerzConvert": HerzConvert,
    "LuminanceConvert": LuminanceConvert,
    "IlluminanceConvert": IlluminanceConvert,
    "AbsorbedDoseConvert": AbsorbedDoseConvert,
    "DoseEquivalentConvert": DoseEquivalentConvert,
    "CatalyticActivityConvert": CatalyticActivityConvert,
    "RadioactivityConvert": RadioactivityConvert,
    "DensityConvertor": DensityConvertor,
    "WavelengthConvertor": WavelengthConvertor,
    "ElectricChargeConvertor": ElectricChargeConvertor,
    "YieldConvertor": YieldConvertor,
    "MassConvertor": MassConvertor,
}